service: aws-node-http-api-project
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  hello:
    handler: dist/functions/hello.handler
    events:
      - httpApi:
          path: /hello
          method: get
  findFirstPositiveSLS:
    handler: dist/functions/findFirstPositiveSLS.handler
    events:
      - httpApi:
          path: /find-positive
          method: post
  findSumOfPositiveSLS:
    handler: dist/functions/findSumOfPositiveSLS.handler
    events:
      - httpApi:
          path: /calculate-sum
          method: post
  findSumAndProductSLS:
    handler: dist/functions/findSumAndProductSLS.handler
    events:
      - httpApi:
          path: /find-sum-and-product
          method: post
  findIndexOfDateSLS:
    handler: dist/functions/findIndexOfDateSLS.handler
    events:
      - httpApi:
          path: /find-index
          method: get
  sortUserInputSLS:
    handler: dist/functions/sortUserInputSLS.handler
    events:
      - httpApi:
          path: /sort-input
          method: post